In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Summer-2022-DM/Classification/heart.csv')

In [ ]:
df

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0     150.0     0      2.3    0   
1     37    1   2     130   250    0        1     187.0     0      3.5    0   
2     41    0   1     130   204    0        0     172.0     0      1.4    2   
3     56    1   1     120   236    0        1     178.0     0      0.8    2   
4     57    0   0     120   354    0        1     163.0     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1     123.0     1      0.2    1   
299   45    1   3     110   264    0        1     132.0     0      1.2    1   
300   68    1   0     144   193    1        1     141.0     0      3.4    1   
301   57    1   0     130   131    0        1     115.0     1      1.2    1   
302   57    0   1     130   236    0        0     174.0     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [ ]:
df.shape

(303, 14)

In [ ]:
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0     150.0     0      2.3    0   
1   37    1   2     130   250    0        1     187.0     0      3.5    0   
2   41    0   1     130   204    0        0     172.0     0      1.4    2   
3   56    1   1     120   236    0        1     178.0     0      0.8    2   
4   57    0   0     120   354    0        1     163.0     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [ ]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    7
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [ ]:
fill= df['thalachh'].median()

In [ ]:
df.thalachh = df.thalachh.fillna(fill)

In [ ]:
df.thalachh

0      150.0
1      187.0
2      172.0
3      178.0
4      163.0
       ...  
298    123.0
299    132.0
300    141.0
301    115.0
302    174.0
Name: thalachh, Length: 303, dtype: float64

In [ ]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [ ]:
x= df.drop(['output'],axis=1)

In [ ]:
x

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0     150.0     0      2.3    0   
1     37    1   2     130   250    0        1     187.0     0      3.5    0   
2     41    0   1     130   204    0        0     172.0     0      1.4    2   
3     56    1   1     120   236    0        1     178.0     0      0.8    2   
4     57    0   0     120   354    0        1     163.0     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1     123.0     1      0.2    1   
299   45    1   3     110   264    0        1     132.0     0      1.2    1   
300   68    1   0     144   193    1        1     141.0     0      3.4    1   
301   57    1   0     130   131    0        1     115.0     1      1.2    1   
302   57    0   1     130   236    0        0     174.0     0      0.0    1   

     caa  thall  
0      0      1  
1      0      2  
2      0      2  
3      0      2  
4      0      2  
..   ...    ...  
298    0      3  
299    0      3  
300    2      3  
301    1      3  
302    1      2  

[303 rows x 13 columns]

In [ ]:
y= df['output']

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

**Splitting**

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30,random_state=1)

# Train(Fit)

In [ ]:
tr=SVC(gamma='auto')
tr.fit(xtrain, ytrain)

SVC(gamma='auto')

In [ ]:
pred= tr.predict(xtest)

In [ ]:
tr.score(xtest,ytest)

0.5604395604395604

In [ ]:
accuracy_score(ytest,pred)

0.5604395604395604

In [ ]:
confusion_matrix(ytest,pred)

array([[ 1, 40],
       [ 0, 50]])

In [ ]:
classification_report(ytest,pred)

'              precision    recall  f1-score   support\n\n           0       1.00      0.02      0.05        41\n           1       0.56      1.00      0.71        50\n\n    accuracy                           0.56        91\n   macro avg       0.78      0.51      0.38        91\nweighted avg       0.76      0.56      0.41        91\n'

In [ ]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       1.00      0.02      0.05        41
           1       0.56      1.00      0.71        50

    accuracy                           0.56        91
   macro avg       0.78      0.51      0.38        91
weighted avg       0.76      0.56      0.41        91



# **Random Forest**

In [ ]:
tr2=RandomForestClassifier(n_estimators=50)
tr2.fit(xtrain, ytrain)

RandomForestClassifier(n_estimators=50)

In [ ]:
pred1 = tr2.predict(xtest)
tr2.score(xtest,ytest)

0.7912087912087912

In [ ]:
confusion_matrix(ytest,pred1)

array([[32,  9],
       [10, 40]])

In [ ]:
classification_report(ytest,pred1)

'              precision    recall  f1-score   support\n\n           0       0.76      0.78      0.77        41\n           1       0.82      0.80      0.81        50\n\n    accuracy                           0.79        91\n   macro avg       0.79      0.79      0.79        91\nweighted avg       0.79      0.79      0.79        91\n'

In [ ]:
print(classification_report(ytest,pred1))

              precision    recall  f1-score   support

           0       0.76      0.78      0.77        41
           1       0.82      0.80      0.81        50

    accuracy                           0.79        91
   macro avg       0.79      0.79      0.79        91
weighted avg       0.79      0.79      0.79        91



# **DecisionTree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(xtrain, ytrain)

DecisionTreeClassifier()

In [ ]:
pred2=dt.predict(xtest)
dt.score(xtest,ytest)

0.7252747252747253

In [80]:
accuracy_score(ytest,pred2)

0.7252747252747253

In [81]:
confusion_matrix(ytest,pred2)

array([[31, 10],
       [15, 35]])

In [ ]:
classification_report(ytest,pred2)

'              precision    recall  f1-score   support\n\n           0       0.67      0.76      0.71        41\n           1       0.78      0.70      0.74        50\n\n    accuracy                           0.73        91\n   macro avg       0.73      0.73      0.72        91\nweighted avg       0.73      0.73      0.73        91\n'

In [ ]:
print(classification_report(ytest,pred2))

              precision    recall  f1-score   support

           0       0.67      0.76      0.71        41
           1       0.78      0.70      0.74        50

    accuracy                           0.73        91
   macro avg       0.73      0.73      0.72        91
weighted avg       0.73      0.73      0.73        91



# **Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

In [ ]:
nb.fit(xtrain, ytrain)
nb.predict(xtest)

array([1, 1, 0, ..., 1, 1, 1])

In [ ]:
nb.score(xtest,ytest)

0.37744444444444447